### ISSUE TITLE
Interprets volume commands as math

### ISSUE THREAD

**Issue by lkellar** [puffyboa/virtual-assistant#19]
when trying to set volume, this happens
````>> set volume 50
50 = 50
>> volume 50
50 = 50
>> set volume to 50
50 = 50

**Comment by jpsank** [comment]
April fools!
I fixed it [https://github.com/puffyboa/virtual-assistant/commit/32f17e9a22589c9de215486ccc85a6526636d6f1](https://github.com/puffyboa/virtual-assistant/commit/32f17e9a22589c9de215486ccc85a6526636d6f1)
