### ISSUE TITLE
collab

### ISSUE THREAD

**Issue by zpitroda** [puffyboa/virtual-assistant#24]
Hi! Was just wondering if you wanted to work together because I made a VA that's kinda similar but hasn't gotten much attention, and it would be cool to kinda combine ours. Thanks!
[My VA](https://github.com/LilChickenz/Jarvis)

**Comment by lkellar** [comment]
We aren't really interested in combining right now, but if you want to add some features and make a PR, that'd be awesome!

**Comment by zpitroda** [comment]
okey :)
